<<<<<<< HEAD
--
dist: xenial
language: ruby
rvm:
  - 2.6.3
services:
  - docker

env:
  - distribution: centos
    version: "7"
  - distribution: centos
    version: "6"
  - distribution: fedora
    version: "29"
  - distribution: fedora
    version: "28"
  - distribution: fedora
    version: "27"
  - distribution: ubuntu
    version: "18.04"
  - distribution: ubuntu
    version: "16.04"
  - distribution: ubuntu
    version: "14.04"
  - distribution: ubuntu
    version: "12.04"
  - distribution: debian
    version: "9"
  - distribution: debian
    version: "8"
  - distribution: debian
    version: "7"
  - distribution: oraclelinux
    version: "7"
  - distribution: oraclelinux
    version: "6"
  - distribution: amazonlinux
    version: "2"
  - distribution: amazonlinux
    version: "1"
  - distribution: opensuse
    version: "42.3"
  - distribution: opensuse
    version: "42.2"
  - distribution: opensuse
    version: "13.2"
  - distribution: archlinux
    version: "rolling"
  - distribution: clearlinux
    version: "rolling"
  - distribution: alpine
    version: "rolling"

before_install:
  - 'sudo docker build --no-cache --rm --file=${distribution}-${version}-ansible/Dockerfile.${distribution}-${version} --tag=diodonfrost/${distribution}-${version}-ansible:latest .'
  - 'sudo apt-get update && sudo apt-get install ansible'
script:
  - 'sudo ansible-galaxy install -r requirement.yml'
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/tmp/ diodonfrost/${distribution}-${version}-ansible:latest > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install -r /tmp/requirement.yml'
  # Test role
  - 'inspec exec tests/inspec -t docker://$(cat ${container_id})'

  # Docker ps
- 'docker ps -a'
=======
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

env:
  - distribution: solaris
    version: "10"
    minor: "11"

install:
  # Install the latest version of Packer with ansible
  - sudo pip install ansible
  - sudo ansible-galaxy install git+https://github.com/diodonfrost/ansible-role-packer
  - sudo ansible-pull -U https://github.com/diodonfrost/ansible-role-packer tests/test.yml

before_script:
  - packer --version
>>>>>>> f733a6929be8f1e90d69491944fd09320b6452c4
