---
services:
  - docker


matrix:
    include:
      - os: linux
        language: ruby
        rvm: 2.5.1
        env:
          - distribution: centos
            version: "7"
            become: sudo
      - os: linux
        language: ruby
        rvm: 2.5.1
        env:
          - distribution: centos
            version: "6"
            become: sudo
      - os: windows
        env:
          - distribution: nanoserver
            version: "1809"
            become: " "


before_install:
  - '${become} docker build --no-cache --rm --file=${distribution}-${version}-ansible/Dockerfile.${distribution}-${version} --tag=diodonfrost/${distribution}-${version}-ansible:latest .'

script:
  - container_id=$(mktemp)
  - '${become} docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/tmp/ diodonfrost/${distribution}-${version}-ansible:latest > "${container_id}"'
  - docker ps
