dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

env:
  - distribution: solaris
    version: "10"
    minor: "11"

install:
  # Install the latest version of Packer with ansible
  - sudo pip3 install ansible
  - sudo ansible-galaxy install git+https://github.com/diodonfrost/ansible-role-packer
  - sudo ansible-pull -U https://github.com/diodonfrost/ansible-role-packer tests/test.yml
