---
dist: xenial
services:
  - docker

matrix:
    include:
      - os: linux
        language: ruby
        rvm: 2.5.1
        env:
          - distribution: centos
            version: "7"
            become: sudo
      - os: linux
        language: ruby
        rvm: 2.5.1
        env:
          - distribution: centos
            version: "6"
            become: sudo
      - os: linux
        language: ruby
        rvm: 2.5.1
        env:
          - distribution: debian
            version: "9"
            become: sudo
      - os: windows
        language: shell
        env:
          - distribution: nanoserver
            version: "1809"
            become: " "


before_install:
  - 'docker -v'

script:
  - container_id=$(mktemp)
  - docker ps
