---

- name: setup Mariadb config file
  template:
    src: server.j2
    dest: "{{ mariadb_config_file }}"
    owner: "{{ mariadb_config_file_owner }}"
    group: "{{ mariadb_config_file_group }}"
    mode: 0644
